const $=id=>document.getElementById(id);
const KEYS={settings:'iamtrader_settings_v2',trades:'iamtrader_trades'};
const defaultSettings={accounts:[{id:'acc-1',name:'Compte Trading',initialCapital:10000,currency:'USD'}],activeAccountId:'acc-1',symbols:['XAUUSD','EURUSD','GBPUSD','NAS100'],capitalMovements:[]};
const state={side:'BUY',move:'deposit'};

function load(){try{const s=JSON.parse(localStorage.getItem(KEYS.settings)||'null');return {...defaultSettings,...s,accounts:s?.accounts?.length?s.accounts:defaultSettings.accounts,symbols:s?.symbols?.length?s.symbols:defaultSettings.symbols,capitalMovements:s?.capitalMovements||[]}}catch{return structuredClone(defaultSettings)}}
function save(s){localStorage.setItem(KEYS.settings,JSON.stringify(s))}
function trades(){try{return JSON.parse(localStorage.getItem(KEYS.trades)||'[]')}catch{return []}}
function money(n){return Number.isFinite(Number(n))?'$'+Number(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}):'—'}
function num(n,d=2){return Number.isFinite(Number(n))?Number(n).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d}):'—'}
function pct(n){return `${num(n)}%`}
function activeAccount(){const s=load();return s.accounts.find(a=>a.id===s.activeAccountId)||s.accounts[0]}
function accountTrades(){const a=activeAccount();return trades().filter(t=>!t.accountId||t.accountId===a.id)}
function movementsFor(a){return load().capitalMovements.filter(m=>m.accountId===a.id)}
function referenceCapital(a){return Number(a.initialCapital||0)+movementsFor(a).reduce((x,m)=>x+(m.type==='deposit'?Number(m.amount):-Number(m.amount)),0)}
function pnl(ts=accountTrades()){return ts.reduce((x,t)=>x+Number(t.netPnl??t.pnl??0),0)}
function equity(a=activeAccount()){return referenceCapital(a)+pnl(accountTrades())}
function stats(ts=accountTrades()){const wins=ts.filter(t=>Number(t.netPnl??t.pnl??0)>0),losses=ts.filter(t=>Number(t.netPnl??t.pnl??0)<0);const grossWin=wins.reduce((x,t)=>x+Number(t.netPnl??t.pnl??0),0),grossLoss=Math.abs(losses.reduce((x,t)=>x+Number(t.netPnl??t.pnl??0),0));const avgWin=wins.length?grossWin/wins.length:0,avgLoss=losses.length?grossLoss/losses.length:0;return{wins,losses,grossWin,grossLoss,avgWin,avgLoss,profitFactor:grossLoss?grossWin/grossLoss:0,winRate:ts.length?wins.length/ts.length*100:0,ratio:avgLoss?avgWin/avgLoss:0,avgR:ts.length?ts.reduce((x,t)=>x+Number(t.rMultiple||0),0)/ts.length:0}}
function validUrl(v){try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)}catch{return false}}
function calc(v){const risk=Math.abs(v.entry-v.stopLoss)*v.quantity*v.contractMultiplier;const reward=Math.abs(v.takeProfit-v.entry);return{riskAmount:risk,riskPercent:risk/v.accountBalance*100,rr:Math.abs(reward/Math.abs(v.entry-v.stopLoss)),grossPnl:Number(v.close)?(v.direction==='BUY'?(v.close-v.entry):(v.entry-v.close))*v.quantity*v.contractMultiplier:0,rMultiple:Number(v.close)?((v.direction==='BUY'?(v.close-v.entry):(v.entry-v.close))*v.quantity*v.contractMultiplier)/risk:0}}
function accountSelects(){const s=load();['accountSelect','qAccount'].forEach(id=>{const el=$(id);if(!el)return;el.innerHTML=s.accounts.map(a=>`<option value="${a.id}">${a.name} · ${money(a.initialCapital)}</option>`).join('');el.value=s.activeAccountId})}
function renderHeader(){const a=activeAccount(),ts=accountTrades(),p=pnl(ts),eq=equity(a);$('accountName').textContent=a.name;$('accountMeta').textContent=`Compte personnel · ${a.currency||'USD'}`;$('headerInitial').textContent=money(a.initialCapital);$('headerEquity').textContent=money(eq);$('headerPnl').textContent=(p>=0?'+':'-')+money(Math.abs(p));$('headerPnl').style.color=p>=0?'var(--accent)':'var(--danger)';$('equityBig').textContent=money(eq);const change=a.initialCapital?p/a.initialCapital*100:0;$('equityChange').textContent=`${change>=0?'+':''}${num(change)}%   (${p>=0?'+':'-'}${money(Math.abs(p))})`}
function setProgress(id,p){const x=Math.max(0,Math.min(100,p));$(id).style.width=x+'%';return x}
function renderDashboard(){const a=activeAccount(),ts=accountTrades(),s=stats(ts),p=pnl(ts),eq=equity(a),ref=referenceCapital(a);$('statPF').textContent=s.grossLoss?num(s.profitFactor):'—';$('statWin').textContent=ts.length?pct(s.winRate):'—';$('statTrades').textContent=ts.length;$('statAvgWin').textContent=money(s.avgWin);$('statAvgLoss').textContent=s.avgLoss?'-$'+num(s.avgLoss):'$0.00';$('statRatio').textContent=s.avgLoss?num(s.ratio):'—';$('profitObjText').textContent=`${money(Math.max(p,0))} / $10,000`;const pp=Math.max(p,0)/10000*100;$('profitPct').textContent=pct(pp);setProgress('profitBar',pp);const daily=Math.abs(ts.filter(t=>new Date(t.dateTime).toDateString()===new Date().toDateString()&&Number(t.netPnl??t.pnl??0)<0).reduce((x,t)=>x+Number(t.netPnl??t.pnl??0),0));$('dailyLossText').textContent=`${money(daily)} / $2,000`;$('dailyLossPct').textContent=pct(daily/2000*100);setProgress('dailyLossBar',daily/2000*100);const dd=Math.max(0,ref-eq);$('ddText').textContent=`${money(dd)} / $8,000`;$('ddPct').textContent=pct(dd/8000*100);setProgress('ddBar',dd/8000*100);const days=new Set(ts.map(t=>new Date(t.dateTime).toDateString())).size;$('daysText').textContent=`${days} / 5 jours`;$('daysPct').textContent=pct(Math.min(days/5*100,100));setProgress('daysBar',days/5*100);renderRows('recentRows',ts.slice(0,8),false);renderScore(s,p,ts,ref);renderPerformance(s,p,ts)}
function renderRows(id,ts,journal){const body=$(id);if(!ts.length){body.innerHTML=`<tr><td colspan="${journal?10:10}" class="empty">Aucun trade enregistré.</td></tr>`;return}body.innerHTML=ts.map(t=>{const v=Number(t.netPnl??t.pnl??0),win=v>=0;const proof=[t.beforeImageUrl,t.afterImageUrl].filter(validUrl);return journal?`<tr><td>${new Date(t.dateTime).toLocaleString('fr-FR')}</td><td>${t.symbol}</td><td><span class="badge ${t.direction==='BUY'?'buy':'sell'}">${t.direction}</span></td><td>${num(t.quantity,2)}</td><td>${num(t.entry,2)}</td><td>${num(t.stopLoss,2)}</td><td>${num(t.takeProfit,2)}</td><td>${num(t.rr)}R</td><td>${money(t.riskAmount)}</td><td>${proof.length?proof.map((u,i)=>`<a class="eye" href="${u}" target="_blank" rel="noopener" title="${i?'Après':'Avant'}"><i class="bi bi-image"></i></a>`).join(' '):'—'}</td></tr>`:`<tr><td>${new Date(t.dateTime).toLocaleDateString('fr-FR')}</td><td>${t.symbol}</td><td><span class="badge ${t.direction==='BUY'?'buy':'sell'}">${t.direction}</span></td><td>${num(t.quantity,2)}</td><td>${num(t.entry,2)}</td><td>${t.close?num(t.close,2):'—'}</td><td style="color:${win?'var(--accent)':'var(--danger)'}">${v>=0?'+':''}${money(v)}</td><td>${num(t.rMultiple)}R</td><td><span class="badge ${win?'win':'loss'}">${win?'Gagnant':'Perdant'}</span></td><td><i class="bi bi-eye eye"></i></td></tr>`}).join('')}
function renderJournal(){const q=($('journalSearch')?.value||'').toUpperCase();const side=$('journalSide')?.value||'ALL';const ts=accountTrades().filter(t=>(!q||String(t.symbol).toUpperCase().includes(q))&&(side==='ALL'||t.direction===side));renderRows('journalRows',ts,true)}
function renderPerformance(s,p,ts){$('perfWins').textContent=s.wins.length;$('perfLosses').textContent=s.losses.length;$('perfPnl').textContent=(p>=0?'+':'-')+money(Math.abs(p));$('perfPnl').style.color=p>=0?'var(--accent)':'var(--danger)';$('perfAvgR').textContent=num(s.avgR)+'R';const complete=ts.length?ts.reduce((x,t)=>x+((t.note?1:0)+(validUrl(t.beforeImageUrl)?1:0)+(validUrl(t.afterImageUrl)?1:0))/3,0)/ts.length*100:100;$('qualityDiscipline').textContent=pct(complete);$('qualityBar').style.width=complete+'%'}
function renderScore(s,p,ts,ref){const risk=ts.length?Math.max(0,100-Math.min(s.avgR<0?50:Math.max(0,(s.avgR*8)),50)):0;const profit=Math.max(0,Math.min(100,50+(ref?p/ref*100:0)*5));const consistency=Math.min(100,ts.length?Math.min(s.winRate,100):0);const discipline=Number(($('qualityDiscipline')?.textContent||'100').replace('%',''));const score=ts.length?Math.round(profit*.35+risk*.2+consistency*.25+discipline*.2):null;$('scoreValue').textContent=score??'—';$('scoreProfit').textContent=ts.length?Math.round(profit)+'/100':'—';$('scoreRisk').textContent=ts.length?Math.round(risk)+'/100':'—';$('scoreConsistency').textContent=ts.length?Math.round(consistency)+'/100':'—';$('scoreDiscipline').textContent=Math.round(discipline)+'/100';$('scoreText').textContent=score===null?'Enregistrez des trades pour calculer votre score.':score>=80?'Très bon niveau de maîtrise. Continuez à protéger votre risque.':score>=60?'Bonne base. Travaillez la régularité pour progresser.':'Votre priorité est la discipline et la maîtrise du risque.'}
function renderAccounts(){const s=load();$('accountList').innerHTML=s.accounts.map(a=>`<div class="account-item ${a.id===s.activeAccountId?'active':''}" data-account="${a.id}"><h4>${a.name}</h4><p>${a.currency||'USD'} · Capital initial</p><strong>${money(a.initialCapital)}</strong></div>`).join('');$('accountList').querySelectorAll('[data-account]').forEach(el=>el.onclick=()=>{s.activeAccountId=el.dataset.account;save(s);accountSelects();renderAll()})}
function renderMarkets(){const s=load();$('symbolChips').innerHTML=s.symbols.map((x,i)=>`<div class="chip">${x}<button data-symbol-index="${i}" title="Supprimer"><i class="bi bi-x"></i></button></div>`).join('');$('qSymbol').innerHTML=s.symbols.map(x=>`<option>${x}</option>`).join('');$('symbolChips').querySelectorAll('[data-symbol-index]').forEach(b=>b.onclick=()=>{s.symbols.splice(Number(b.dataset.symbolIndex),1);if(!s.symbols.length)s.symbols=['XAUUSD'];save(s);renderMarkets()})}
function renderCapital(){const a=activeAccount(),ms=movementsFor(a),dep=ms.filter(m=>m.type==='deposit').reduce((x,m)=>x+Number(m.amount),0),wit=ms.filter(m=>m.type==='withdrawal').reduce((x,m)=>x+Number(m.amount),0);$('capInitial').textContent=money(a.initialCapital);$('capDeposits').textContent='+'+money(dep);$('capWithdrawals').textContent='-'+money(wit);$('capReference').textContent=money(referenceCapital(a));$('capEquity').textContent=money(equity(a));$('movementRows').innerHTML=ms.length?ms.slice().reverse().map(m=>`<div class="movement ${m.type==='withdrawal'?'withdraw':''}"><div><b>${m.type==='deposit'?'Ajout de capital':'Retrait de capital'}</b><br><small>${new Date(m.date).toLocaleString('fr-FR')} ${m.note?'· '+m.note:''}</small></div><b>${m.type==='deposit'?'+':'-'}${money(m.amount)}</b></div>`).join(''):'<div class="empty">Aucun mouvement de capital.</div>'}
function renderSettings(){const a=activeAccount();$('setAccountName').value=a.name;$('setInitialCapital').value=a.initialCapital}
function renderAll(){renderHeader();renderDashboard();renderJournal();renderAccounts();renderMarkets();renderCapital();renderSettings();accountSelects();updateQuickAccount()}
function navigate(view){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(('view-'+view))?.classList.add('active');document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelectorAll('.subtab').forEach(b=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'});if(view==='journal')renderJournal()}
function updateQuickAccount(){const a=activeAccount();$('qAccount').value=a.id}
function quickPreview(){const entry=Number($('qEntry').value),sl=Number($('qSL').value),tp=Number($('qTP').value),qty=Number($('qQty').value),mult=Number($('qMult').value)||1,a=activeAccount(),bal=referenceCapital(a);if(!entry||!sl||!tp||!qty||entry===sl){$('qRR').textContent='—';$('qRisk').textContent='—';$('qRiskPct').textContent='—';$('qSLDist').textContent='—';$('qTPDist').textContent='—';$('qExposure').textContent='—';return}const c=calc({entry,stopLoss:sl,takeProfit:tp,quantity:qty,contractMultiplier:mult,accountBalance:bal});$('qRR').textContent=num(c.rr)+'R';$('qRisk').textContent=money(c.riskAmount);$('qRiskPct').textContent=pct(c.riskPercent);$('qSLDist').textContent=num(Math.abs(entry-sl),2);$('qTPDist').textContent=num(Math.abs(tp-entry),2);$('qExposure').textContent=money(Math.abs(entry*qty*mult));$('qRiskStatus').textContent=c.riskPercent<=1?'Risque maîtrisé · ≤ 1% du capital.':c.riskPercent<=2?'Risque modéré · surveillez votre exposition.':'Risque élevé · vérifiez votre taille de position.'}
function setup(){document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.view)));$('mobileMenu').onclick=()=>$('sidebar').classList.toggle('open');$('accountSelect').onchange=e=>{const s=load();s.activeAccountId=e.target.value;save(s);renderAll()};['qEntry','qSL','qTP','qQty','qMult'].forEach(id=>$(id).addEventListener('input',quickPreview));document.querySelectorAll('.side-btn').forEach(b=>b.onclick=()=>{state.side=b.dataset.side;document.querySelectorAll('.side-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');quickPreview()});document.querySelectorAll('.move-btn').forEach(b=>b.onclick=()=>{state.move=b.dataset.move;document.querySelectorAll('.move-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active')});$('journalSearch').oninput=renderJournal;$('journalSide').onchange=renderJournal;$('clearTrades').onclick=()=>{if(confirm('Effacer tous les trades du compte actif ?')){const a=activeAccount();localStorage.setItem(KEYS.trades,JSON.stringify(trades().filter(t=>t.accountId&&t.accountId!==a.id)));renderAll()}};$('addAccount').onclick=()=>{const name=$('newAccountName').value.trim(),capital=Number($('newAccountCapital').value);if(!name||capital<0)return;const s=load(),a={id:'acc-'+Date.now(),name,initialCapital:capital,currency:'USD'};s.accounts.push(a);s.activeAccountId=a.id;save(s);$('newAccountName').value='';$('newAccountCapital').value='';renderAll()};$('addSymbol').onclick=()=>{const v=$('newSymbol').value.trim().toUpperCase();if(!v)return;const s=load();if(!s.symbols.includes(v))s.symbols.push(v);save(s);$('newSymbol').value='';renderMarkets()};$('addMovement').onclick=()=>{const amount=Number($('movementAmount').value);if(!amount||amount<=0)return;const s=load();s.capitalMovements.push({id:'mov-'+Date.now(),accountId:s.activeAccountId,type:state.move,amount,note:$('movementNote').value.trim(),date:new Date().toISOString()});save(s);$('movementAmount').value='';$('movementNote').value='';renderAll()};$('saveAccountSettings').onclick=()=>{const s=load(),a=s.accounts.find(x=>x.id===s.activeAccountId);a.name=$('setAccountName').value.trim()||a.name;a.initialCapital=Math.max(0,Number($('setInitialCapital').value)||0);save(s);renderAll()};$('tradeForm').onsubmit=saveTrade;document.querySelectorAll('.range-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.range-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});$('qDate').value=new Date().toISOString().slice(0,16)}
async function saveTrade(e){e.preventDefault();$('quickError').hidden=true;const a=activeAccount(),entry=Number($('qEntry').value),sl=Number($('qSL').value),tp=Number($('qTP').value),qty=Number($('qQty').value),mult=Number($('qMult').value)||1;if(!entry||!sl||!tp||!qty){$('quickError').textContent='Veuillez compléter les prix et la quantité.';$('quickError').hidden=false;return}if((state.side==='BUY'&&!(sl<entry&&tp>entry))||(state.side==='SELL'&&!(sl>entry&&tp<entry))){$('quickError').textContent='Pour ce sens, vérifiez la position du Stop Loss et du Take Profit.';$('quickError').hidden=false;return}const before=$('qBefore').value.trim(),after=$('qAfter').value.trim();if((before&&!validUrl(before))||(after&&!validUrl(after))){$('quickError').textContent='Les preuves doivent être des liens http/https valides.';$('quickError').hidden=false;return}const base={accountId:a.id,symbol:$('qSymbol').value,direction:state.side,entry,stopLoss:sl,takeProfit:tp,quantity:qty,contractMultiplier:mult,accountBalance:referenceCapital(a),dateTime:$('qDate').value,note:$('qNote').value.trim(),beforeImageUrl:before,afterImageUrl:after};let data;try{const r=await fetch('/api/trades/calculate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(base)});if(r.ok)data=await r.json()}catch{}if(!data)data=calc({...base,close:0});const t={...base,...data,id:'trade-'+Date.now(),createdAt:new Date().toISOString()};const list=trades();list.unshift(t);localStorage.setItem(KEYS.trades,JSON.stringify(list.slice(0,500)));e.target.reset();state.side='BUY';document.querySelectorAll('.side-btn').forEach((b,i)=>b.classList.toggle('active',i===0));$('qMult').value='1';$('qDate').value=new Date().toISOString().slice(0,16);accountSelects();updateQuickAccount();quickPreview();renderAll();navigate('journal')}
setup();renderAll();quickPreview();