const $=id=>document.getElementById(id);
const KEYS={settings:'iamtrader_settings_v2',trades:'iamtrader_trades'};
const DEFAULT={pairs:[{symbol:'XAUUSD',active:true},{symbol:'EURUSD',active:true},{symbol:'GBPUSD',active:true},{symbol:'NAS100',active:true}],accounts:[],capitalMovements:[],activeAccountId:null};
const titles={dashboard:['ESPACE DE TRAVAIL','Vue d’ensemble'],quick:['TRADING / SAISIE','Nouveau trade'],journal:['TRADING / HISTORIQUE','Journal'],analytics:['ANALYSE','Performance'],evaluation:['ÉVALUATION','Score du trader'],accounts:['GESTION','Comptes'],settings:['GESTION / CONFIGURATION','Paramètres']};
const uid=p=>p+'_'+Date.now()+'_'+Math.random().toString(36).slice(2,8);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=(x,c='USD')=>Number.isFinite(Number(x))?`${c==='USD'?'$':c+' '}${Number(x).toLocaleString('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2})}`:'—';
const num=(x,d=2)=>Number.isFinite(Number(x))?Number(x).toLocaleString('fr-FR',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
function settings(){try{const s=JSON.parse(localStorage.getItem(KEYS.settings)||'{}');return {...DEFAULT,...s,pairs:Array.isArray(s.pairs)?s.pairs:DEFAULT.pairs,accounts:Array.isArray(s.accounts)?s.accounts:[],capitalMovements:Array.isArray(s.capitalMovements)?s.capitalMovements:[]}}catch{return structuredClone(DEFAULT)}}
function save(s){localStorage.setItem(KEYS.settings,JSON.stringify(s))}
function trades(){try{return JSON.parse(localStorage.getItem(KEYS.trades)||'[]')}catch{return[]}}
function saveTrades(v){localStorage.setItem(KEYS.trades,JSON.stringify(v.slice(0,500)))}
function active(){const s=settings();return s.accounts.find(a=>a.id===s.activeAccountId)||s.accounts[0]||null}
function acctTrades(id=active()?.id){return id?trades().filter(t=>t.accountId===id):[]}
function referenceCapital(a){if(!a)return 0;return Number(a.initialCapital||0)+settings().capitalMovements.filter(m=>m.accountId===a.id).reduce((v,m)=>v+(m.type==='deposit'?Number(m.amount):-Number(m.amount)),0)}
function pnl(ts){return ts.reduce((v,t)=>v+(Number(t.netPnl)||0),0)}
function equity(a,ts){return referenceCapital(a)+pnl(ts)}
function drawdown(a,ts){let peak=referenceCapital(a),run=peak,max=0;ts.slice().reverse().forEach(t=>{run+=Number(t.netPnl)||0;peak=Math.max(peak,run);if(peak>0)max=Math.max(max,(peak-run)/peak*100)});return num(max,2)+'%'}
function score(ts){if(!ts.length)return{risk:0,consistency:0,discipline:0,total:0};const avgRisk=ts.reduce((v,t)=>v+(Number(t.riskPercent)||0),0)/ts.length,avgRR=ts.reduce((v,t)=>v+(Number(t.rr)||0),0)/ts.length,context=ts.filter(t=>String(t.note||'').trim().length>=8||t.beforeImageUrl||t.afterImageUrl).length;const risk=Math.max(0,Math.min(100,Math.round(100-Math.max(0,avgRisk-1)*25)));const consistency=Math.max(0,Math.min(100,Math.round(Math.min(ts.length/20,1)*70+Math.min(Math.max(avgRR,0)/3,1)*30)));const discipline=Math.max(0,Math.min(100,Math.round(context/ts.length*70+Math.min(ts.length/10,1)*30)));return{risk,consistency,discipline,total:Math.round(risk*.4+consistency*.3+discipline*.3)}}
function calc(v){const dist=Math.abs(v.entry-v.sl);if(![v.entry,v.sl,v.tp,v.qty,v.mult,v.capital].every(Number.isFinite)||v.qty<=0||v.mult<=0||v.capital<=0||dist<=0)throw Error('Vérifiez les champs numériques et le capital du compte.');return{riskAmount:dist*v.qty*v.mult,riskPercent:dist*v.qty*v.mult/v.capital*100,rr:Math.abs(v.tp-v.entry)/dist}}
function validUrl(v){if(!v)return null;try{const u=new URL(v);if(!['http:','https:'].includes(u.protocol))throw 0;return u.href}catch{throw Error('Le lien image doit être une URL http(s) valide.')}}
function setText(id,v){if($(id))$(id).textContent=v}
function toast(msg){const el=$('toast');if(!el)return;el.textContent=msg;el.classList.remove('hidden');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.add('hidden'),2200)}
function navigate(page){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id==='page-'+page));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const t=titles[page]||titles.dashboard;setText('eyebrow',t[0]);setText('title',t[1]);$('sidebar')?.classList.remove('open');$('overlay')?.classList.remove('show');renderAll()}
function renderSelectors(){const s=settings(),a=active(),options=s.accounts.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');if($('qAccount')){$('qAccount').innerHTML='<option value="">Sélectionner un compte</option>'+options;$('qAccount').value=a?.id||''}if($('mAccount')){$('mAccount').innerHTML=options||'<option value="">Créez d’abord un compte</option>';$('mAccount').value=a?.id||''}setText('accountName',a?.name||'Sélectionner');setText('sideAccount',a?.name||'Aucun compte');setText('sideEquity',a?money(equity(a,acctTrades()),a.currency):'—');const sel=$('qSymbol'),old=sel?.value;if(sel){sel.innerHTML='<option value="">Sélectionner un actif</option>'+s.pairs.filter(p=>p.active).map(p=>`<option>${esc(p.symbol)}</option>`).join('');if(s.pairs.some(p=>p.symbol===old&&p.active))sel.value=old}renderAccountMenu()}
function renderAccountMenu(){const el=$('accountMenu'),s=settings(),a=active();if(!el)return;el.innerHTML=`<div class="border-b border-[#243B53] p-4"><div class="text-[9px] font-semibold tracking-[.1em] muted">COMPTE ACTIF</div></div>`+(s.accounts.map(x=>`<button data-id="${esc(x.id)}" class="account-option m-2 block w-[calc(100%-16px)] rounded-md border border-[#243B53] p-3 text-left ${x.id===a?.id?'bg-[#0A192F] border-[#00C796]':''}"><div class="flex justify-between gap-2"><b class="truncate text-[13px]">${esc(x.name)}</b><span class="mono text-[11px] text-[#00C796]">${money(equity(x,acctTrades(x.id)),x.currency)}</span></div><div class="mt-1 text-[10px] muted">${esc(x.broker||x.type||'Compte de trading')}</div></button>`).join('')||'<div class="p-4 text-[12px] muted">Aucun compte.</div>')+`<button data-page="settings" class="m-2 w-[calc(100%-16px)] rounded-md border border-dashed border-[#243B53] p-3 text-left text-[12px] font-semibold text-[#00C796]">＋ Ajouter un compte</button>`;el.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{const s=settings();s.activeAccountId=b.dataset.id;save(s);el.classList.add('hidden');renderAll()});el.querySelector('[data-page]')?.addEventListener('click',()=>{el.classList.add('hidden');navigate('settings')})}
function renderDashboard(){const a=active(),ts=acctTrades(),cap=referenceCapital(a),eq=equity(a,ts),today=new Date().toISOString().slice(0,10),todayP=ts.filter(t=>String(t.dateTime).slice(0,10)===today).reduce((v,t)=>v+(Number(t.netPnl)||0),0),closed=ts.filter(t=>Number.isFinite(Number(t.netPnl))),wins=closed.filter(t=>Number(t.netPnl)>0).length,wr=closed.length?wins/closed.length*100:0,avgRisk=ts.length?ts.reduce((v,t)=>v+(Number(t.riskPercent)||0),0)/ts.length:0;setText('dCapital',a?money(cap,a.currency):'—');setText('dEquity',a?money(eq,a.currency):'—');setText('dToday',a?money(todayP,a.currency):'—');setText('dDD',a?drawdown(a,ts):'—');setText('dScore',ts.length?`${score(ts).total}/100`:'—');setText('tradeCount',`${ts.length} trade${ts.length>1?'s':''}`);setText('avgRisk',ts.length?num(avgRisk)+'%':'—');setText('winRate',closed.length?num(wr,1)+'%':'—');if($('riskBar'))$('riskBar').style.width=Math.min(100,avgRisk/2*100)+'%';if($('winBar'))$('winBar').style.width=wr+'%';setText('riskStatus',avgRisk<=1?'Risque maîtrisé':avgRisk<=2?'À surveiller':'Risque élevé');$('noAccount')?.classList.toggle('hidden',!!a);const rows=ts.slice(0,6).map(t=>`<tr class="border-b border-[#243B53]"><td class="px-5 py-3 muted">${esc(new Date(t.dateTime).toLocaleDateString('fr-FR'))}</td><td class="px-5 py-3 font-semibold">${esc(t.symbol)}</td><td class="px-5 py-3 ${t.direction==='BUY'?'text-[#00C796]':'text-[#C7A86B]'}">${t.direction}</td><td class="px-5 py-3 mono">${num(t.entry)}</td><td class="px-5 py-3 mono">${num(t.rr)}R</td><td class="px-5 py-3 text-[10px] muted">${t.netPnl!=null?(Number(t.netPnl)>=0?'GAIN':'PERTE'):'PLANIFIÉ'}${t.beforeImageUrl||t.afterImageUrl?' · PREUVE':''}</td></tr>`).join('');if($('recentRows'))$('recentRows').innerHTML=rows||'<tr><td colspan="6" class="px-5 py-10 text-center muted">Aucun trade pour ce compte.</td></tr>';const bars=$('equityBars');if(!bars)return;if(!closed.length){bars.innerHTML='';$('equityEmpty')?.classList.remove('hidden')}else{$('equityEmpty')?.classList.add('hidden');let run=cap;const series=closed.slice().reverse().map(t=>run+=Number(t.netPnl)||0),min=Math.min(cap,...series),max=Math.max(cap,...series),range=max-min||1;bars.innerHTML=series.map(v=>`<div class="flex-1 rounded-t bg-[#00C796]" title="${money(v,a.currency)}" style="height:${Math.max(5,(v-min)/range*100)}%"></div>`).join('')}}
function renderJournal(){const a=active(),ts=acctTrades();setText('journalContext',a?`${a.name} · ${ts.length} trade${ts.length>1?'s':''}`:'Aucun compte actif');if(!$('journalRows'))return;$('journalRows').innerHTML=ts.map(t=>`<tr class="border-b border-[#243B53]"><td class="px-4 py-3 muted">${esc(new Date(t.dateTime).toLocaleString('fr-FR'))}</td><td class="px-4 py-3 font-semibold">${esc(t.symbol)}</td><td class="px-4 py-3 ${t.direction==='BUY'?'text-[#00C796]':'text-[#C7A86B]'}">${t.direction}</td><td class="px-4 py-3 mono">${num(t.entry)}</td><td class="px-4 py-3 mono">${num(t.sl)}</td><td class="px-4 py-3 mono">${num(t.tp)}</td><td class="px-4 py-3 mono">${num(t.rr)}R</td><td class="px-4 py-3 mono">${money(t.riskAmount,a?.currency)}</td><td class="px-4 py-3">${t.beforeImageUrl?`<a class="text-[#00C796]" target="_blank" rel="noopener" href="${esc(t.beforeImageUrl)}">Avant</a>`:''}${t.beforeImageUrl&&t.afterImageUrl?' · ':''}${t.afterImageUrl?`<a class="text-[#00C796]" target="_blank" rel="noopener" href="${esc(t.afterImageUrl)}">Après</a>`:''||'—'}</td></tr>`).join('')||'<tr><td colspan="9" class="px-4 py-12 text-center muted">Aucun trade enregistré.</td></tr>'}
function renderAnalytics(){const a=active(),ts=acctTrades(),cl=ts.filter(t=>Number.isFinite(Number(t.netPnl))),wins=cl.filter(t=>Number(t.netPnl)>0),loss=cl.filter(t=>Number(t.netPnl)<0),grossW=wins.reduce((v,t)=>v+Number(t.netPnl),0),grossL=Math.abs(loss.reduce((v,t)=>v+Number(t.netPnl),0)),avgRR=ts.length?ts.reduce((v,t)=>v+(Number(t.rr)||0),0)/ts.length:0,wr=cl.length?wins.length/cl.length*100:0,pf=grossL?grossW/grossL:0,avgRisk=ts.length?ts.reduce((v,t)=>v+(Number(t.riskPercent)||0),0)/ts.length:0;const cards=[['Capitaux propres',a?money(equity(a,ts),a.currency):'—'],['P&L net',a?money(pnl(ts),a.currency):'—'],['Taux de réussite',cl.length?num(wr,1)+'%':'—'],['Profit factor',cl.length?num(pf):'—'],['R:R moyen',ts.length?num(avgRR)+'R':'—'],['Trades',String(ts.length)],['Risque moyen',ts.length?num(avgRisk)+'%':'—'],['Drawdown max',a?drawdown(a,ts):'—']];if($('analyticsGrid'))$('analyticsGrid').innerHTML=cards.map(c=>`<div class="metric"><div class="text-[10px] font-semibold muted">${c[0].toUpperCase()}</div><div class="mt-3 mono text-[22px] font-semibold">${c[1]}</div></div>`).join('')}
function renderEvaluation(){const ts=acctTrades(),s=score(ts);setText('scoreBig',ts.length?s.total:'—');if($('scoreBreakdown'))$('scoreBreakdown').innerHTML=`<h2 class="text-[20px] font-bold">Décomposition du score</h2><div class="mt-6 space-y-5">${[['Maîtrise du risque',s.risk],['Régularité',s.consistency],['Discipline',s.discipline]].map(x=>`<div><div class="flex justify-between text-[13px]"><span>${x[0]}</span><span class="mono">${x[1]}/100</span></div><div class="mt-2 h-1 rounded bg-[#243B53]"><div class="h-1 rounded bg-[#00C796]" style="width:${x[1]}%"></div></div></div>`).join('')}</div>`}
function renderAccounts(){const s=settings();if(!$('accountsGrid'))return;$('accountsGrid').innerHTML=s.accounts.map(a=>{const ts=acctTrades(a.id),eq=equity(a,ts);return `<div class="surface p-5"><div class="flex justify-between gap-3"><div><div class="text-[10px] muted">${esc(a.type||'Compte de trading')}</div><h2 class="mt-1 text-[20px] font-bold">${esc(a.name)}</h2><div class="mt-1 text-[12px] muted">${esc(a.broker||'Indépendant')}</div></div><span class="pill ${a.id===s.activeAccountId?'text-[#00C796]':''}">${a.id===s.activeAccountId?'ACTIF':'PRÊT'}</span></div><div class="mt-6 grid grid-cols-2 gap-3"><div><div class="text-[9px] muted">RÉFÉRENCE</div><div class="mt-1 mono text-[14px]">${money(referenceCapital(a),a.currency)}</div></div><div><div class="text-[9px] muted">EQUITY</div><div class="mt-1 mono text-[14px] text-[#00C796]">${money(eq,a.currency)}</div></div></div><button data-account="${esc(a.id)}" class="btn secondary mt-5 w-full">${a.id===s.activeAccountId?'Compte actif':'Utiliser ce compte'}</button></div>`}).join('')||'<div class="surface p-6 text-[13px] muted">Aucun compte. Créez-en un dans Paramètres.</div>';$('accountsGrid').querySelectorAll('[data-account]').forEach(b=>b.onclick=()=>{const s=settings();s.activeAccountId=b.dataset.account;save(s);renderAll();toast('Compte actif mis à jour')})}
function renderSettings(){const s=settings();if($('settingsAccounts')){$('settingsAccounts').innerHTML=s.accounts.map(a=>`<div class="surface flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><b class="text-[14px]">${esc(a.name)}</b><div class="mt-1 text-[11px] muted">${esc(a.broker||a.type||'Compte de trading')} · ${money(referenceCapital(a),a.currency)}</div></div><button data-use="${esc(a.id)}" class="btn secondary">${a.id===s.activeAccountId?'Actif':'Utiliser'}</button></div>`).join('')||'<div class="surface p-5 text-[13px] muted">Créez votre premier compte pour commencer.</div>';$('settingsAccounts').querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>{const s=settings();s.activeAccountId=b.dataset.use;save(s);renderAll();toast('Compte sélectionné')})}if($('settingsPairs')){$('settingsPairs').innerHTML=s.pairs.map(p=>`<div class="surface flex items-center justify-between p-4"><div><b class="text-[14px]">${esc(p.symbol)}</b><div class="mt-1 text-[10px] muted">${p.active?'Disponible dans Nouveau trade':'Masqué dans Nouveau trade'}</div></div><button data-pair="${esc(p.symbol)}" class="pill ${p.active?'text-[#00C796]':''}">${p.active?'ACTIF':'INACTIF'}</button></div>`).join('');$('settingsPairs').querySelectorAll('[data-pair]').forEach(b=>b.onclick=()=>{const s=settings(),p=s.pairs.find(z=>z.symbol===b.dataset.pair);if(p)p.active=!p.active;save(s);renderAll()})}const a=active(),moves=s.capitalMovements.filter(m=>m.accountId===a?.id),dep=moves.filter(m=>m.type==='deposit').reduce((v,m)=>v+Number(m.amount),0),wit=moves.filter(m=>m.type==='withdrawal').reduce((v,m)=>v+Number(m.amount),0);if($('capitalSummary'))$('capitalSummary').innerHTML=[['Capital initial',a?money(a.initialCapital,a.currency):'—'],['Ajouts de capital',a?money(dep,a.currency):'—'],['Retraits',a?money(wit,a.currency):'—'],['Capital de référence',a?money(referenceCapital(a),a.currency):'—']].map(c=>`<div class="metric"><div class="text-[10px] muted">${c[0].toUpperCase()}</div><div class="mt-3 mono text-[19px]">${c[1]}</div></div>`).join('');if($('capitalMoves'))$('capitalMoves').innerHTML=`<div class="border-b border-[#243B53] p-4"><b class="text-[14px]">Historique du capital</b></div>`+(moves.map(m=>`<div class="flex items-center justify-between border-b border-[#243B53] px-4 py-3 text-[12px]"><span>${esc(m.date)} · ${esc(m.note||'')}</span><span class="mono ${m.type==='deposit'?'text-[#00C796]':'text-[#E05252]'}">${m.type==='deposit'?'+':'-'}${money(m.amount,a?.currency)}</span></div>`).join('')||'<div class="p-5 text-[12px] muted">Aucun mouvement de capital.</div>')}
function renderAll(){renderSelectors();renderDashboard();renderJournal();renderAnalytics();renderEvaluation();renderAccounts();renderSettings()}
function preview(){const a=active();try{const r=calc({entry:Number($('qEntry').value),sl:Number($('qSL').value),tp:Number($('qTP').value),qty:Number($('qQty').value),mult:Number($('qMult').value),capital:referenceCapital(a)});setText('pRR',num(r.rr)+'R');setText('pRisk',money(r.riskAmount,a?.currency));setText('pRiskPct',num(r.riskPercent)+'%')}catch{setText('pRR','—');setText('pRisk','—');setText('pRiskPct','—')}}
function imagePreview(input,box){const v=input?.value.trim();if(!box)return;if(!v){box.classList.add('hidden');box.innerHTML='';return}try{const u=new URL(v);if(!['http:','https:'].includes(u.protocol))throw 0;box.innerHTML=`<img src="${esc(u.href)}" alt="Aperçu" loading="lazy">`;box.classList.remove('hidden');box.querySelector('img').onerror=()=>{box.classList.add('hidden');box.innerHTML=''}}catch{box.classList.add('hidden');box.innerHTML=''}}
document.addEventListener('click',e=>{const p=e.target.closest('[data-page]');if(p)navigate(p.dataset.page)});
$('menu')?.addEventListener('click',()=>{$('sidebar')?.classList.add('open');$('overlay')?.classList.add('show')});$('overlay')?.addEventListener('click',()=>{$('sidebar')?.classList.remove('open');$('overlay')?.classList.remove('show')});$('switcher')?.addEventListener('click',e=>{e.stopPropagation();$('accountMenu')?.classList.toggle('hidden')});document.addEventListener('click',e=>{if(!$('accountMenu')?.contains(e.target)&&e.target.id!=='switcher')$('accountMenu')?.classList.add('hidden')});
['qEntry','qSL','qTP','qQty','qMult'].forEach(id=>$(id)?.addEventListener('input',preview));$('qBefore')?.addEventListener('input',()=>imagePreview($('qBefore'),$('beforePreview')));$('qAfter')?.addEventListener('input',()=>imagePreview($('qAfter'),$('afterPreview')));
$('qAccount')?.addEventListener('change',()=>{const s=settings();if(s.accounts.some(a=>a.id===$('qAccount').value)){s.activeAccountId=$('qAccount').value;save(s);renderAll();preview()}});
$('tradeForm')?.addEventListener('submit',e=>{e.preventDefault();const a=active(),err=$('qError');try{if(!a)throw Error('Créez ou sélectionnez un compte.');if(!$('qSymbol').value)throw Error('Sélectionnez un actif.');const r=calc({entry:Number($('qEntry').value),sl:Number($('qSL').value),tp:Number($('qTP').value),qty:Number($('qQty').value),mult:Number($('qMult').value),capital:referenceCapital(a)});const before=validUrl($('qBefore').value.trim()),after=validUrl($('qAfter').value.trim()),close=$('qClose').value.trim();let netPnl=null;if(close!==''){const cp=Number(close);if(!Number.isFinite(cp))throw Error('Prix de clôture invalide.');netPnl=($('qDirection').value==='BUY'?(cp-Number($('qEntry').value)):(Number($('qEntry').value)-cp))*Number($('qQty').value)*Number($('qMult').value)}const t={id:uid('trade'),accountId:a.id,symbol:$('qSymbol').value,direction:$('qDirection').value,dateTime:$('qDate').value||new Date().toISOString(),entry:Number($('qEntry').value),sl:Number($('qSL').value),tp:Number($('qTP').value),qty:Number($('qQty').value),mult:Number($('qMult').value),riskAmount:r.riskAmount,riskPercent:r.riskPercent,rr:r.rr,netPnl,beforeImageUrl:before,afterImageUrl:after,note:$('qNote').value.trim()};const all=trades();all.unshift(t);saveTrades(all);e.target.reset();$('qQty').value=1;$('qMult').value=1;$('qDate').value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);$('beforePreview')?.classList.add('hidden');$('afterPreview')?.classList.add('hidden');if(err)err.classList.add('hidden');renderAll();toast('Trade enregistré');navigate('journal')}catch(x){if(err){err.textContent=x.message;err.classList.remove('hidden')}}});
$('accountForm')?.addEventListener('submit',e=>{e.preventDefault();const s=settings(),name=$('aName').value.trim(),capital=Number($('aCapital').value);if(!name||!Number.isFinite(capital)||capital<0){toast('Renseignez le nom et un capital valide');return}const a={id:uid('acct'),name,broker:$('aBroker').value.trim(),type:$('aType').value||'Compte de trading',currency:$('aCurrency').value,initialCapital:capital};s.accounts.push(a);if(!s.activeAccountId)s.activeAccountId=a.id;save(s);e.target.reset();renderAll();toast('Compte créé')});
$('pairForm')?.addEventListener('submit',e=>{e.preventDefault();const s=settings(),input=$('pSymbol'),symbol=input?.value.trim().toUpperCase();if(!symbol)return;if(!s.pairs.some(p=>p.symbol===symbol))s.pairs.push({symbol,active:true});save(s);e.target.reset();renderAll();toast('Actif ajouté')});
$('movementForm')?.addEventListener('submit',e=>{e.preventDefault();const s=settings(),amount=Number($('mAmount').value),account=s.accounts.find(a=>a.id===$('mAccount').value);if(!account||!Number.isFinite(amount)||amount<=0){toast('Vérifiez le compte et le montant');return}s.capitalMovements.push({id:uid('mov'),accountId:account.id,type:$('mType').value,amount,date:$('mDate').value,note:$('mNote').value.trim()});save(s);e.target.reset();$('mDate').value=new Date().toISOString().slice(0,10);renderAll();toast('Mouvement enregistré')});
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.settings-tab').forEach(x=>x.classList.toggle('hidden',x.id!=='settings-'+b.dataset.tab))}));
$('qDate')?.setAttribute('value',new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16));if($('qDate'))$('qDate').value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);if($('mDate'))$('mDate').value=new Date().toISOString().slice(0,10);renderAll();