const $ = (id) => document.getElementById(id);
const pages = ['dashboard','quick','journal'];
const genericPages = ['performance','risk','behavior','score','discipline','accounts','settings'];
const titles = {dashboard:['OVERVIEW','Dashboard'],quick:['JOURNAL / QUICK TRADE','Quick Trade'],journal:['TRADING / JOURNAL','Trade Journal'],performance:['ANALYTICS','Performance'],risk:['ANALYTICS','Risk'],behavior:['ANALYTICS','Behavior'],score:['EVALUATION','Trader Score'],discipline:['EVALUATION','Discipline'],accounts:['ACCOUNT','Trading Accounts'],settings:['ACCOUNT','Settings']};

function formatMoney(n){return Number.isFinite(n)?`$${n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`:'—'}
function formatNum(n){return Number.isFinite(n)?n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:4}):'—'}
function values(){return {entry:Number($('entry')?.value),stopLoss:Number($('stopLoss')?.value),takeProfit:Number($('takeProfit')?.value),quantity:Number($('quantity')?.value),contractMultiplier:Number($('contractMultiplier')?.value),accountBalance:Number($('accountBalance')?.value)}}
function calculate(v){if(![v.entry,v.stopLoss,v.takeProfit,v.quantity,v.contractMultiplier,v.accountBalance].every(Number.isFinite))throw new Error('Tous les champs numériques sont requis.');if(v.quantity<=0||v.contractMultiplier<=0||v.accountBalance<=0)throw new Error('Quantity, contract multiplier et solde doivent être supérieurs à 0.');const riskDistance=Math.abs(v.entry-v.stopLoss);if(riskDistance===0)throw new Error('Le Stop Loss doit être différent de l’Entry.');const riskAmount=riskDistance*v.quantity*v.contractMultiplier;return{riskAmount,riskPercent:riskAmount/v.accountBalance*100,rr:Math.abs(v.takeProfit-v.entry)/riskDistance}}
function preview(){if(!$('entry'))return;try{const v=values(),r=calculate(v);$('rr').textContent=`${formatNum(r.rr)}R`;$('riskAmount').textContent=formatMoney(r.riskAmount);$('riskPercent').textContent=`${formatNum(r.riskPercent)}%`;$('riskFormula').textContent=formatNum(Math.abs(v.entry-v.stopLoss));$('rewardFormula').textContent=formatNum(Math.abs(v.takeProfit-v.entry));$('accountBalanceLabel').textContent=formatMoney(v.accountBalance)}catch{$('rr').textContent='—';$('riskAmount').textContent='—';$('riskPercent').textContent='—';$('riskFormula').textContent='Entry ↔ SL';$('rewardFormula').textContent='Entry ↔ TP'}$('directionBox').textContent=$('direction').value==='BUY'?'BUY · Long exposure':'SELL · Short exposure'}
function getTrades(){try{return JSON.parse(localStorage.getItem('iamtrader_trades')||'[]')}catch{return[]}}
function renderJournal(){const trades=getTrades();if($('tradeRows'))$('tradeRows').innerHTML=trades.length?trades.map(t=>`<tr class="border-b border-white/5"><td class="py-3 text-slate-500">${new Date(t.dateTime).toLocaleString('fr-FR')}</td><td class="py-3 font-bold">${t.symbol}</td><td class="py-3 ${t.direction==='BUY'?'text-mint':'text-gold'}">${t.direction}</td><td class="py-3">${formatNum(t.entry)}</td><td class="py-3">${formatNum(t.stopLoss)}</td><td class="py-3">${formatNum(t.takeProfit)}</td><td class="py-3 text-mint">${formatNum(t.rr)}R</td><td class="py-3">${formatMoney(t.riskAmount)}</td></tr>`).join(''):'<tr><td colspan="8" class="px-3 py-10 text-center text-xs text-slate-600">Aucune opération enregistrée.</td></tr>'}
function renderDashboard(){const trades=getTrades();if(!$('dashboardRows'))return;$('dashboardRows').innerHTML=trades.slice(0,5).map(t=>`<tr class="border-b border-white/5"><td class="py-3 font-bold">${t.symbol}</td><td class="py-3 ${t.direction==='BUY'?'text-mint':'text-gold'}">${t.direction}</td><td class="py-3 font-mono">${formatNum(t.entry)}</td><td class="py-3 font-mono text-mint">${formatNum(t.rr)}R</td><td class="py-3 font-mono">${formatMoney(t.riskAmount)}</td><td class="py-3"><span class="rounded-full border border-white/10 px-2 py-1 text-[8px] text-slate-500">PLANNED</span></td></tr>`).join('')||'<tr><td colspan="6" class="py-10 text-center text-xs text-slate-600">Aucune opération récente. Commencez avec Quick Trade.</td></tr>'}
function navigate(page){const isGeneric=genericPages.includes(page);document.querySelectorAll('.page').forEach(el=>el.classList.add('hidden'));if(isGeneric){$('page-generic').classList.remove('hidden');$('genericTitle').textContent=titles[page][1]}else $('page-'+page).classList.remove('hidden');document.querySelectorAll('.nav-item').forEach(b=>{b.classList.remove('active','bg-mint/10','text-mint');b.classList.add('text-slate-400');if(b.dataset.page===page){b.classList.add('active');b.classList.remove('text-slate-400')}});$('topEyebrow').textContent=titles[page][0];$('topTitle').textContent=titles[page][1];$('sidebar').classList.add('-translate-x-full');$('overlay').classList.add('hidden');if(page==='journal')renderJournal()}

document.querySelectorAll('[data-page]').forEach(el=>el.addEventListener('click',()=>navigate(el.dataset.page)));
$('menuBtn')?.addEventListener('click',()=>{$('sidebar').classList.remove('-translate-x-full');$('overlay').classList.remove('hidden')});$('overlay')?.addEventListener('click',()=>{$('sidebar').classList.add('-translate-x-full');$('overlay').classList.add('hidden')});

const quickFields=['entry','stopLoss','takeProfit','quantity','contractMultiplier','accountBalance'];quickFields.concat(['direction']).forEach(id=>$(id)?.addEventListener('input',preview));
$('tradeForm')?.addEventListener('submit',e=>{e.preventDefault();$('error').hidden=true;try{const v=values(),r=calculate(v),payload={symbol:$('symbol').value.trim().toUpperCase(),direction:$('direction').value,...v,dateTime:$('dateTime').value,note:$('note').value.trim(),...r};if(!payload.symbol)throw new Error('Asset / Symbol est requis.');const trades=getTrades();trades.unshift(payload);localStorage.setItem('iamtrader_trades',JSON.stringify(trades.slice(0,100)));renderJournal();renderDashboard();e.target.reset();$('contractMultiplier').value='1';$('accountBalance').value='10000';$('dateTime').value=new Date().toISOString().slice(0,16);preview();navigate('journal')}catch(err){$('error').textContent=err.message;$('error').hidden=false}});
$('clearTrades')?.addEventListener('click',()=>{localStorage.removeItem('iamtrader_trades');renderJournal();renderDashboard()});
if($('dateTime'))$('dateTime').value=new Date().toISOString().slice(0,16);preview();renderJournal();renderDashboard();
