const $ = (id) => document.getElementById(id);

const KEYS = { settings:'iamtrader_settings_v2', trades:'iamtrader_trades' };
const DEFAULT_SETTINGS = {
  pairs: [{symbol:'XAUUSD',active:true},{symbol:'EURUSD',active:true},{symbol:'GBPUSD',active:true},{symbol:'NAS100',active:true}],
  accounts: [],
  capitalMovements: [],
  activeAccountId: null
};

const titles = {
  dashboard:['WORKSPACE','Dashboard'], quick:['TRADING / QUICK ENTRY','Quick Trade'], journal:['TRADING / HISTORY','Trade Journal'],
  performance:['ANALYTICS','Performance'], risk:['ANALYTICS','Risk Management'], behavior:['ANALYTICS','Behavior'],
  score:['EVALUATION','Trader Score'], discipline:['EVALUATION','Discipline'], accounts:['MANAGEMENT','Trading Accounts'], settings:['MANAGEMENT','Settings']
};
const genericPages = ['performance','risk','behavior','score','discipline'];
const money = (n,currency='USD') => Number.isFinite(Number(n)) ? `${currency==='USD'?'$':currency+' '}${Number(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}` : '—';
const num = (n) => Number.isFinite(Number(n)) ? Number(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:4}) : '—';
const uid = (prefix) => `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;
const esc = (v) => String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

function readSettings(){ try { return {...DEFAULT_SETTINGS,...JSON.parse(localStorage.getItem(KEYS.settings)||'{}')} } catch { return structuredClone(DEFAULT_SETTINGS); } }
function saveSettings(s){ localStorage.setItem(KEYS.settings,JSON.stringify(s)); }
function getTrades(){ try{return JSON.parse(localStorage.getItem(KEYS.trades)||'[]')}catch{return[]} }
function saveTrades(t){localStorage.setItem(KEYS.trades,JSON.stringify(t.slice(0,300)));}
function activeAccount(){const s=readSettings();return s.accounts.find(a=>a.id===s.activeAccountId)||s.accounts[0]||null;}
function accountTrades(accountId=activeAccount()?.id){return accountId?getTrades().filter(t=>t.accountId===accountId):[];}
function capitalReference(account){if(!account)return 0;const s=readSettings();const moves=s.capitalMovements.filter(m=>m.accountId===account.id);return Number(account.initialCapital||0)+moves.reduce((sum,m)=>sum+(m.type==='deposit'?Number(m.amount): -Number(m.amount)),0);}
function realizedPnl(trades){return trades.reduce((sum,t)=>sum+(Number(t.netPnl)||Number(t.pnl)||0),0);}
function currentEquity(account,trades){return capitalReference(account)+realizedPnl(trades);}
function calculate(v){
  const fields=[v.entry,v.stopLoss,v.takeProfit,v.quantity,v.contractMultiplier,v.accountBalance];
  if(!fields.every(Number.isFinite))throw new Error('Tous les champs numériques requis doivent être valides.');
  if(v.quantity<=0||v.contractMultiplier<=0||v.accountBalance<=0)throw new Error('La taille, le multiplier et le capital doivent être supérieurs à 0.');
  const riskDistance=Math.abs(v.entry-v.stopLoss); if(!riskDistance)throw new Error('Entry et Stop Loss doivent être différents.');
  const rewardDistance=Math.abs(v.takeProfit-v.entry);
  const riskAmount=riskDistance*v.quantity*v.contractMultiplier;
  return {riskAmount,riskPercent:riskAmount/v.accountBalance*100,rr:rewardDistance/riskDistance};
}
function fileToDataUrl(file){return new Promise((resolve,reject)=>{if(!file)return resolve(null);if(!file.type.startsWith('image/'))return reject(new Error('Le fichier doit être une image.'));if(file.size>2*1024*1024)return reject(new Error('Chaque capture doit rester sous 2 MB.'));const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('Impossible de lire la capture.'));r.readAsDataURL(file);});}
function scoreMetrics(trades){
  if(!trades.length)return {risk:0,consistency:0,discipline:0,score:0};
  const avgRisk=trades.reduce((s,t)=>s+(Number(t.riskPercent)||0),0)/trades.length;
  const avgRR=trades.reduce((s,t)=>s+(Number(t.rr)||0),0)/trades.length;
  const risk=Math.max(0,Math.min(100,Math.round(100-Math.max(0,avgRisk-1)*25)));
  const consistency=Math.max(0,Math.min(100,Math.round(Math.min(trades.length/20,1)*70+Math.min(Math.max(avgRR,0)/3,1)*30)));
  const contextual=trades.filter(t=>String(t.note||'').trim().length>=8||t.beforeCapture||t.afterCapture).length;
  const discipline=Math.max(0,Math.min(100,Math.round(contextual/trades.length*70+Math.min(trades.length/10,1)*30)));
  return {risk,consistency,discipline,score:Math.round(risk*.4+consistency*.3+discipline*.3)};
}
function setText(id,value){if($(id))$(id).textContent=value;}
function renderAccountSelectors(){
  const s=readSettings(), current=activeAccount();
  const accountOptions=s.accounts.map(a=>`<option value="${esc(a.id)}">${esc(a.name)}</option>`).join('');
  if($('tradeAccount')){$('tradeAccount').innerHTML='<option value="">Sélectionner</option>'+accountOptions; if(current)$('tradeAccount').value=current.id;}
  if($('movementAccount')){$('movementAccount').innerHTML=accountOptions||'<option value="">Créer un compte d’abord</option>'; if(current)$('movementAccount').value=current.id;}
  setText('activeAccountName',current?current.name:'Select account');
  setText('sidebarAccount',current?current.name:'No account selected');
  setText('sidebarEquity',current?money(currentEquity(current,accountTrades(current.id)),current.currency):'—');
  if($('quickNoAccount'))$('quickNoAccount').classList.toggle('hidden',!!current);
  if($('noAccountBanner'))$('noAccountBanner').classList.toggle('hidden',!!current);
  if(current && $('accountBalance'))$('accountBalance').value=capitalReference(current)||current.initialCapital||'';
  renderAccountMenu();
}
function renderAccountMenu(){
  const s=readSettings(), current=activeAccount(), menu=$('accountMenu'); if(!menu)return;
  menu.innerHTML=`<div class="border-b border-[#243B53] p-4"><div class="text-[10px] font-semibold tracking-[.1em] text-[#8B969E]">SELECT ACCOUNT</div></div>${s.accounts.map(a=>{const eq=currentEquity(a,accountTrades(a.id));return `<button data-switch-account="${esc(a.id)}" class="account-option ${current?.id===a.id?'active':''} m-2 block w-[calc(100%-16px)] p-3 text-left"><div class="flex items-center justify-between gap-3"><span class="truncate text-[13px] font-semibold">${esc(a.name)}</span><span class="mono text-[11px] text-[#00C796]">${money(eq,a.currency)}</span></div><div class="mt-1 text-[10px] text-[#8B969E]">${esc(a.broker||a.type||'Trading account')}</div></button>`}).join('')||'<div class="p-5 text-[13px] text-[#8B969E]">Aucun compte. Créez-en un dans Settings.</div>'}<button data-page="settings" class="m-2 w-[calc(100%-16px)] rounded-lg border border-dashed border-[#243B53] p-3 text-left text-[12px] font-semibold text-[#00C796]">＋ Add account</button>`;
  menu.querySelectorAll('[data-switch-account]').forEach(b=>b.addEventListener('click',()=>{const x=readSettings();x.activeAccountId=b.dataset.switchAccount;saveSettings(x);menu.classList.add('hidden');renderAll();}));
  menu.querySelector('[data-page="settings"]')?.addEventListener('click',()=>{menu.classList.add('hidden');navigate('settings');});
}
function setDefaultDate(){if($('dateTime')&&!$('dateTime').value){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());$('dateTime').value=d.toISOString().slice(0,16);}}
function preview(){
  if(!$('entry'))return;
  try{const account=activeAccount(),v={entry:Number($('entry').value),stopLoss:Number($('stopLoss').value),takeProfit:Number($('takeProfit').value),quantity:Number($('quantity').value),contractMultiplier:Number($('contractMultiplier').value),accountBalance:Number($('accountBalance').value)||capitalReference(account)};const r=calculate(v);setText('rr',`${num(r.rr)}R`);setText('riskAmount',money(r.riskAmount,account?.currency||'USD'));setText('riskPercent',`${num(r.riskPercent)}%`);setText('riskFormula',num(Math.abs(v.entry-v.stopLoss)));setText('rewardFormula',num(Math.abs(v.takeProfit-v.entry)));}catch{setText('rr','—');setText('riskAmount','—');setText('riskPercent','—');setText('riskFormula','—');setText('rewardFormula','—');}
  if($('directionBox'))$('directionBox').textContent=$('direction').value==='BUY'?'BUY · Long':'SELL · Short';
}
function populatePairs(){const s=readSettings(),sel=$('symbol');if(!sel)return;const current=sel.value;sel.innerHTML='<option value="">Sélectionner une paire / actif</option>'+s.pairs.filter(p=>p.active).map(p=>`<option value="${esc(p.symbol)}">${esc(p.symbol)}</option>`).join('');if(s.pairs.some(p=>p.symbol===current&&p.active))sel.value=current;}
function renderDashboard(){
  const a=activeAccount(),trades=accountTrades(),closed=trades.filter(t=>t.status==='CLOSED'||t.result==='WIN'||t.result==='LOSS'),pnl=realizedPnl(trades),capital=capitalReference(a),equity=currentEquity(a,trades),m=scoreMetrics(trades),today=new Date().toISOString().slice(0,10),todayPnl=trades.filter(t=>String(t.dateTime||'').slice(0,10)===today).reduce((s,t)=>s+(Number(t.netPnl)||0),0);
  setText('metricCapital',a?money(capital,a.currency):'—');setText('metricEquity',a?money(equity,a.currency):'—');setText('metricToday',a?money(todayPnl,a.currency):'—');setText('metricScore',a&&trades.length?`${m.score}/100`:'—');setText('dashboardTradeCount',`${trades.length} trade${trades.length>1?'s':''}`);
  const avgRisk=trades.length?trades.reduce((s,t)=>s+(Number(t.riskPercent)||0),0)/trades.length:0;setText('riskPerTrade',trades.length?`${num(avgRisk)}%`:'—');setText('riskStatus',avgRisk<=1?'Controlled':avgRisk<=2?'Watch':'High');if($('riskBar'))$('riskBar').style.width=`${Math.min(100,avgRisk/2*100)}%`;
  const peak=Math.max(capital,...trades.map((_,i)=>capital+trades.slice(i+1).reduce((s,t)=>s+(Number(t.netPnl)||0),0)));const dd=peak?Math.max(0,(peak-equity)/peak*100):0;setText('drawdownValue',`${num(dd)}%`);if($('drawdownBar'))$('drawdownBar').style.width=`${Math.min(100,dd*10)}%`;
  const rows=trades.slice(0,6).map(t=>`<tr class="border-b border-[#243B53]"><td class="px-5 py-3 text-[#8B969E]">${esc(new Date(t.dateTime).toLocaleDateString('fr-FR'))}</td><td class="px-5 py-3 font-semibold">${esc(t.symbol)}</td><td class="px-5 py-3 ${t.direction==='BUY'?'text-[#00C796]':'text-[#C7A86B]'}">${t.direction}</td><td class="px-5 py-3 mono">${num(t.entry)}</td><td class="px-5 py-3 mono">${num(t.rr)}R</td><td class="px-5 py-3 text-[11px] text-[#8B969E]">${t.status||'PLANNED'}${t.beforeCapture||t.afterCapture?' · EVIDENCE':''}</td></tr>`).join('');if($('dashboardRows'))$('dashboardRows').innerHTML=rows||'<tr><td colspan="6" class="px-5 py-10 text-center text-[13px] text-[#8B969E]">Aucun trade pour ce compte.</td></tr>';
  const bars=$('equityBars');if(bars){if(!closed.length){bars.innerHTML='';$('equityEmpty')?.classList.remove('hidden');}else{$('equityEmpty')?.classList.add('hidden');let run=capital;const series=closed.slice().reverse().map(t=>run+=Number(t.netPnl)||0);const min=Math.min(capital,...series),max=Math.max(capital,...series),range=max-min||1;bars.innerHTML=series.map(v=>`<div title="${money(v,a?.currency)}" class="flex-1 rounded-t bg-[#00C796]" style="height:${Math.max(5,((v-min)/range)*100)}%"></div>`).join('');}}
}
function renderJournal(){const a=activeAccount(),trades=accountTrades();setText('journalContext',a?`${a.name} · ${trades.length} trades`:'Aucun compte actif');if(!$('tradeRows'))return;$('tradeRows').innerHTML=trades.length?trades.map(t=>`<tr class="border-b border-[#243B53]"><td class="px-5 py-3 text-[#8B969E]">${esc(new Date(t.dateTime).toLocaleString('fr-FR'))}</td><td class="px-5 py-3 font-semibold">${esc(t.symbol)}</td><td class="px-5 py-3 ${t.direction==='BUY'?'text-[#00C796]':'text-[#C7A86B]'}">${t.direction}</td><td class="px-5 py-3 mono">${num(t.entry)}</td><td class="px-5 py-3 mono">${num(t.stopLoss)}</td><td class="px-5 py-3 mono">${num(t.takeProfit)}</td><td class="px-5 py-3 mono">${num(t.rr)}R</td><td class="px-5 py-3 mono">${money(t.riskAmount,a?.currency)}</td><td class="px-5 py-3 text-[11px] text-[#8B969E]">${[t.beforeCapture?'Before':'',t.afterCapture?'After':''].filter(Boolean).join(' + ')||'—'}</td></tr>`).join(''):'<tr><td colspan="9" class="px-5 py-12 text-center text-[13px] text-[#8B969E]">Aucun trade enregistré pour ce compte.</td></tr>'}
function renderAccounts(){const s=readSettings(),grid=$('accountsGrid'),list=$('settingsAccountList');const html=s.accounts.map(a=>{const tr=accountTrades(a.id),eq=currentEquity(a,tr);return `<div class="surface p-5"><div class="flex items-start justify-between gap-3"><div><div class="text-[11px] text-[#8B969E]">${esc(a.type)}</div><h3 class="mt-1 text-[20px] font-bold">${esc(a.name)}</h3><div class="mt-1 text-[12px] text-[#8B969E]">${esc(a.broker||'Independent')}</div></div>${s.activeAccountId===a.id?'<span class="rounded-full border border-[#00C796]/40 px-2 py-1 text-[10px] text-[#00C796]">ACTIVE</span>':''}</div><div class="mt-6 grid grid-cols-2 gap-3"><div><div class="text-[10px] text-[#8B969E]">CAPITAL</div><div class="mt-1 mono text-[15px]">${money(capitalReference(a),a.currency)}</div></div><div><div class="text-[10px] text-[#8B969E]">EQUITY</div><div class="mt-1 mono text-[15px] text-[#00C796]">${money(eq,a.currency)}</div></div></div><button data-select-account="${esc(a.id)}" class="btn btn-secondary mt-5 w-full">${s.activeAccountId===a.id?'Account active':'Use this account'}</button></div>`}).join('');if(grid)grid.innerHTML=html||'<div class="surface p-6 text-[13px] text-[#8B969E]">Aucun compte configuré. Ajoutez votre premier compte dans Settings.</div>';if(list)list.innerHTML=s.accounts.map(a=>`<button data-select-account="${esc(a.id)}" class="account-option flex w-full items-center justify-between p-3 text-left"><span><span class="block text-[13px] font-semibold">${esc(a.name)}</span><span class="text-[10px] text-[#8B969E]">${esc(a.broker||a.type)}</span></span><span class="mono text-[11px] text-[#00C796]">${money(currentEquity(a,accountTrades(a.id)),a.currency)}</span></button>`).join('')||'<div class="text-[13px] text-[#8B969E]">No accounts yet.</div>';document.querySelectorAll('[data-select-account]').forEach(b=>b.addEventListener('click',()=>{const x=readSettings();x.activeAccountId=b.dataset.selectAccount;saveSettings(x);renderAll();navigate('dashboard')}));}
function renderPairs(){const s=readSettings();if($('pairList'))$('pairList').innerHTML=s.pairs.map(p=>`<div class="flex items-center justify-between rounded-lg border border-[#243B53] p-3"><div><span class="mono text-[13px] font-semibold">${esc(p.symbol)}</span><span class="ml-2 text-[10px] ${p.active?'text-[#00C796]':'text-[#8B969E]'}">${p.active?'ACTIVE':'OFF'}</span></div><button data-toggle-pair="${esc(p.symbol)}" class="text-[11px] text-[#8B969E]">${p.active?'Disable':'Enable'}</button></div>`).join('')||'<div class="text-[13px] text-[#8B969E]">Aucune paire.</div>';const a=activeAccount();setText('pairAccountSummary',a?`${a.name} utilise le trading universe global pour Quick Trade.`:'Sélectionnez un compte pour voir son contexte.');document.querySelectorAll('[data-toggle-pair]').forEach(b=>b.addEventListener('click',()=>{const x=readSettings(),p=x.pairs.find(p=>p.symbol===b.dataset.togglePair);if(p)p.active=!p.active;saveSettings(x);renderAll();}));}
function renderCapital(){const a=activeAccount(),s=readSettings();if(!a){if($('capitalOverview'))$('capitalOverview').innerHTML='<div class="text-[13px] text-[#8B969E]">Créez un compte d’abord.</div>';return}const moves=s.capitalMovements.filter(m=>m.accountId===a.id).sort((x,y)=>String(y.date).localeCompare(String(x.date)));if($('capitalOverview'))$('capitalOverview').innerHTML=`<div class="grid grid-cols-2 gap-3"><div class="metric p-4"><div class="text-[10px] text-[#8B969E]">INITIAL</div><div class="mt-2 mono">${money(a.initialCapital,a.currency)}</div></div><div class="metric p-4"><div class="text-[10px] text-[#8B969E]">REFERENCE</div><div class="mt-2 mono text-[#00C796]">${money(capitalReference(a),a.currency)}</div></div></div><div class="mt-3 text-[12px] text-[#8B969E]">Equity actuelle : <span class="mono text-[#E7ECEE]">${money(currentEquity(a,accountTrades(a.id)),a.currency)}</span></div>`;if($('movementList'))$('movementList').innerHTML=moves.map(m=>`<div class="flex items-center justify-between rounded-lg border border-[#243B53] p-3"><div><div class="text-[12px] font-semibold">${m.type==='deposit'?'Deposit':'Withdrawal'}</div><div class="text-[10px] text-[#8B969E]">${esc(m.date||'')} ${esc(m.note||'')}</div></div><div class="mono text-[12px] ${m.type==='deposit'?'text-[#00C796]':'text-[#E05252]'}">${m.type==='deposit'?'+':'-'}${money(m.amount,a.currency)}</div></div>`).join('')||'<div class="text-[13px] text-[#8B969E]">Aucun mouvement.</div>';}
function renderGeneric(){const a=activeAccount();setText('genericAccount',a?.name||'No account');setText('genericTrades',accountTrades().length);}
function renderAll(){renderAccountSelectors();populatePairs();renderDashboard();renderJournal();renderAccounts();renderPairs();renderCapital();renderGeneric();preview();}
function navigate(page){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));const target=genericPages.includes(page)?'page-generic':`page-${page}`;$(target)?.classList.add('active');document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));setText('eyebrow',titles[page]?.[0]||'IAMTRADER');setText('pageTitle',titles[page]?.[1]||page);if(page==='settings')showSettingsTab('accounts');if(page==='journal')renderJournal();if(page==='dashboard')renderDashboard();document.body.classList.remove('sidebar-open');}
function showSettingsTab(tab){document.querySelectorAll('[data-settings-tab]').forEach(b=>b.classList.toggle('active',b.dataset.settingsTab===tab));document.querySelectorAll('.settings-panel').forEach(p=>p.classList.add('hidden'));$(`settings-${tab}`)?.classList.remove('hidden');if(tab==='pairs')renderPairs();if(tab==='capital')renderCapital();}
function toast(msg){const t=$('toast');if(!t)return;t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200);}

document.querySelectorAll('[data-page]').forEach(el=>el.addEventListener('click',()=>navigate(el.dataset.page)));
$('accountSwitcher')?.addEventListener('click',()=>$('accountMenu')?.classList.toggle('hidden'));
document.addEventListener('click',e=>{if(!$('accountSwitcher')?.contains(e.target)&&!$('accountMenu')?.contains(e.target))$('accountMenu')?.classList.add('hidden');});
$('menuBtn')?.addEventListener('click',()=>document.body.classList.toggle('sidebar-open'));
$('mobileOverlay')?.addEventListener('click',()=>document.body.classList.remove('sidebar-open'));
document.querySelectorAll('[data-settings-tab]').forEach(b=>b.addEventListener('click',()=>showSettingsTab(b.dataset.settingsTab)));
['entry','stopLoss','takeProfit','quantity','contractMultiplier','accountBalance','direction'].forEach(id=>$(id)?.addEventListener('input',preview));
$('tradeAccount')?.addEventListener('change',()=>{const s=readSettings();s.activeAccountId=$('tradeAccount').value||s.activeAccountId;saveSettings(s);renderAll();});
$('beforeCapture')?.addEventListener('change',async e=>{try{const d=await fileToDataUrl(e.target.files[0]);if(d){$('beforePreview').src=d;$('beforePreview').classList.remove('hidden');$('beforeLabel').classList.add('hidden');$('beforePreview').closest('.capture')?.classList.add('has-image');$('beforeCapture').dataset.data=d;}}catch(err){toast(err.message);e.target.value='';}});
$('afterCapture')?.addEventListener('change',async e=>{try{const d=await fileToDataUrl(e.target.files[0]);if(d){$('afterPreview').src=d;$('afterPreview').classList.remove('hidden');$('afterLabel').classList.add('hidden');$('afterPreview').closest('.capture')?.classList.add('has-image');$('afterCapture').dataset.data=d;}}catch(err){toast(err.message);e.target.value='';}});
$('accountForm')?.addEventListener('submit',e=>{e.preventDefault();const s=readSettings();const account={id:uid('acct'),name:$('accountName').value.trim(),broker:$('accountBroker').value.trim(),type:$('accountType').value,initialCapital:Number($('initialCapital').value),currency:($('accountCurrency').value||'USD').trim().toUpperCase(),riskPerTrade:Number($('riskPerTrade').value)||1,timezone:$('accountTimezone').value||'UTC'};if(!account.name||!Number.isFinite(account.initialCapital)||account.initialCapital<0)return toast('Nom et capital initial requis.');s.accounts.push(account);s.activeAccountId=account.id;saveSettings(s);e.target.reset();$('accountCurrency').value='USD';$('riskPerTrade').value='1';$('accountTimezone').value='UTC';renderAll();toast('Compte créé.');navigate('dashboard');});
$('pairForm')?.addEventListener('submit',e=>{e.preventDefault();const symbol=$('pairSymbol').value.trim().toUpperCase();if(!symbol)return;const s=readSettings();if(s.pairs.some(p=>p.symbol===symbol))return toast('Cet actif existe déjà.');s.pairs.push({symbol,active:true});saveSettings(s);e.target.reset();renderAll();toast(`${symbol} ajouté.`);});
$('movementForm')?.addEventListener('submit',e=>{e.preventDefault();const s=readSettings(),accountId=$('movementAccount').value,amount=Number($('movementAmount').value);if(!accountId||!Number.isFinite(amount)||amount<=0)return toast('Compte et montant requis.');s.capitalMovements.push({id:uid('move'),accountId,type:$('movementType').value,amount,date:$('movementDate').value||new Date().toISOString().slice(0,10),note:$('movementNote').value.trim()});saveSettings(s);e.target.reset();renderAll();toast('Mouvement enregistré.');});
$('tradeForm')?.addEventListener('submit',async e=>{e.preventDefault();$('error').classList.add('hidden');const account=activeAccount();try{if(!account)throw new Error('Créez ou sélectionnez un compte avant le trade.');const accountBalance=capitalReference(account);const v={entry:Number($('entry').value),stopLoss:Number($('stopLoss').value),takeProfit:Number($('takeProfit').value),quantity:Number($('quantity').value),contractMultiplier:Number($('contractMultiplier').value),accountBalance};const r=calculate(v);const symbol=$('symbol').value.trim().toUpperCase();if(!symbol)throw new Error('Sélectionnez un actif depuis le Trading Universe.');const [beforeCapture,afterCapture]=await Promise.all([fileToDataUrl($('beforeCapture').files[0]),fileToDataUrl($('afterCapture').files[0])]);const payload={id:uid('trade'),accountId:account.id,symbol,direction:$('direction').value,...v,dateTime:$('dateTime').value||new Date().toISOString(),note:$('note').value.trim(),...r,status:'PLANNED',beforeCapture,afterCapture};const trades=getTrades();trades.unshift(payload);saveTrades(trades);e.target.reset();$('contractMultiplier').value='1';$('dateTime').value='';renderAll();toast('Trade enregistré dans le compte actif.');navigate('journal');}catch(err){$('error').textContent=err.message;$('error').classList.remove('hidden');}});
$('clearTrades')?.addEventListener('click',()=>{const a=activeAccount();if(!a)return;if(confirm(`Effacer les trades locaux de ${a.name} ?`)){saveTrades(getTrades().filter(t=>t.accountId!==a.id));renderAll();toast('Trades du compte supprimés.');}});

setDefaultDate();renderAll();