(()=>{
'use strict';
const TRADES_KEY='iamtrader_trades', SETTINGS_KEY='iamtrader_settings_v2';
const $=id=>document.getElementById(id), num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const read=()=>{try{const v=JSON.parse(localStorage.getItem(TRADES_KEY)||'[]');return Array.isArray(v)?v:[]}catch{return[]}};
const write=v=>localStorage.setItem(TRADES_KEY,JSON.stringify(v.slice(0,500)));
const settings=()=>{try{return JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')}catch{return{}}};
function outcome(t){const d=String(t.direction||'').toUpperCase(),c=num(t.close),tp=num(t.tp),sl=num(t.sl);if(c===null)return{status:'OPEN',label:'Ouvert',win:null};if(tp!==null&&((d==='BUY'&&c>=tp)||(d==='SELL'&&c<=tp)))return{status:'TP_REACHED',label:'TP atteint',win:true};if(sl!==null&&((d==='BUY'&&c<=sl)||(d==='SELL'&&c>=sl)))return{status:'SL_HIT',label:'SL touché',win:false};const p=num(t.netPnl)||0;return{status:p>0?'MANUAL_WIN':p<0?'MANUAL_LOSS':'BREAKEVEN',label:p>0?'Sortie gagnante':p<0?'Sortie perdante':'Break-even',win:p>0?true:p<0?false:null}};
function normalize(){const a=read();let changed=false;for(const t of a){const o=outcome(t);if(t.outcomeStatus!==o.status||t.outcomeLabel!==o.label||t.isWin!==o.win){t.outcomeStatus=o.status;t.outcomeLabel=o.label;t.isWin=o.win;t.isLoss=o.win===null?null:!o.win;changed=true}}if(changed)write(a);return a}
function addFields(){const f=$('quickForm');if(!f||f.querySelector('[data-iam-psych]'))return;const wrap=document.createElement('section');wrap.dataset.iamPsych='1';wrap.className='mt-5 rounded-2xl border border-[#dce8ee] bg-[#fbfdfe] p-5';wrap.innerHTML=`<div class="text-[10px] font-extrabold tracking-[.14em] text-[#00a67e]">PSYCHOLOGIE & DISCIPLINE</div><div class="mt-1 text-[16px] font-extrabold text-[#08243a]">Contexte de décision</div><div class="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><label><span class="label">État avant</span><select id="qEmotion" class="field"><option value="">Sélectionner</option><option>Calme</option><option>Confiant</option><option>Incertain</option><option>Stressé</option><option>FOMO</option><option>Frustré</option><option>Pressé</option><option>Excité</option></select></label><label><span class="label">Confiance /10</span><input id="qConfidence" class="field" type="number" min="1" max="10"></label><label><span class="label">Stress /10</span><input id="qStress" class="field" type="number" min="1" max="10"></label><label><span class="label">Fatigue /10</span><input id="qFatigue" class="field" type="number" min="1" max="10"></label><label><span class="label">Raison de l'entrée</span><select id="qReason" class="field"><option value="">Sélectionner</option><option>Setup planifié</option><option>Opportunité exceptionnelle</option><option>FOMO</option><option>Revenge trading</option><option>Impulsion</option><option>Autre</option></select></label><label><span class="label">Plan respecté</span><select id="qPlan" class="field"><option value="">Sélectionner</option><option>Oui</option><option>Partiellement</option><option>Non</option></select></label><label><span class="label">État après sortie</span><select id="qAfterEmotion" class="field"><option value="">Sélectionner</option><option>Calme</option><option>Satisfait</option><option>Déçu</option><option>Frustré</option><option>En colère</option><option>Euphorique</option><option>Stressé</option><option>Soulagé</option></select></label></div><p class="mt-3 text-[10px] text-[#6b7f93]">Ces données sont enregistrées avec le trade. Elles ne servent pas à juger votre humeur, mais à mesurer la qualité de vos décisions.</p>`;f.appendChild(wrap)}
function snapshot(){return{beforeEmotion:$('qEmotion')?.value||null,confidence:num($('qConfidence')?.value),stress:num($('qStress')?.value),fatigue:num($('qFatigue')?.value),entryReason:$('qReason')?.value||null,planRespect:$('qPlan')?.value||null,afterEmotion:$('qAfterEmotion')?.value||null}}
function savePsychology(s){const before=read();const ids=new Set(before.map(t=>String(t.id)));setTimeout(()=>{const a=read();let target=a.find(t=>t.id===window.__iamEditingTradeId);if(!target){const candidates=a.filter(t=>!ids.has(String(t.id)));target=candidates[candidates.length-1]||null}if(!target)return;target.psychology={...(target.psychology||{}),...s};Object.assign(target,{beforeEmotion:s.beforeEmotion,confidence:s.confidence,stress:s.stress,fatigue:s.fatigue,entryReason:s.entryReason,planRespect:s.planRespect,afterEmotion:s.afterEmotion});const o=outcome(target);Object.assign(target,{outcomeStatus:o.status,outcomeLabel:o.label,isWin:o.win,isLoss:o.win===null?null:!o.win});write(a);window.dispatchEvent(new CustomEvent('iamtrader:data-updated'))},500)}
function fillExisting(){const f=$('quickForm'),id=f?.dataset.editingId;if(!id)return;const t=read().find(x=>String(x.id)===String(id)),p=t?.psychology||t;if(!p)return;[['qEmotion','beforeEmotion'],['qConfidence','confidence'],['qStress','stress'],['qFatigue','fatigue'],['qReason','entryReason'],['qPlan','planRespect'],['qAfterEmotion','afterEmotion']].forEach(([i,k])=>{const e=$(i);if(e&&p[k]!=null)e.value=p[k]})}
function analyse(ts){const documented=ts.filter(t=>t.psychology&&(t.psychology.beforeEmotion||t.psychology.entryReason||t.psychology.confidence!=null));const avg=k=>{const v=documented.map(t=>num(t.psychology?.[k])).filter(x=>x!==null);return v.length?v.reduce((a,b)=>a+b,0)/v.length:null};const group=reason=>{const x=documented.filter(t=>t.psychology?.entryReason===reason),wins=x.filter(t=>t.isWin===true).length,pnl=x.reduce((a,t)=>a+(num(t.netPnl)||0),0);return{n:x.length,wr:x.length?wins/x.length*100:null,pnl}};const planned=documented.filter(t=>t.psychology?.planRespect),respected=planned.filter(t=>t.psychology.planRespect==='Oui').length;return{n:documented.length,confidence:avg('confidence'),stress:avg('stress'),fatigue:avg('fatigue'),plan:planned.length?respected/planned.length*100:null,fomo:group('FOMO'),revenge:group('Revenge trading'),impulse:group('Impulsion')}}
function renderAnalysis(){const s=settings(),id=s.activeAccountId||s.accounts?.[0]?.id,ts=read().filter(t=>!id||t.accountId===id),m=analyse(ts);document.querySelectorAll('#page-dashboard,#page-journal,#page-analytics').forEach(page=>{let box=page.querySelector('#iamPsychologyAnalysis');if(!box){box=document.createElement('section');box.id='iamPsychologyAnalysis';box.className='mt-5 rounded-2xl border border-[#dce8ee] bg-white p-5 shadow-sm';page.appendChild(box)}const v=(x,d=1)=>x==null?'—':x.toFixed(d);box.innerHTML=`<div class="text-[10px] font-extrabold tracking-[.14em] text-[#00a67e]">ANALYSE COMPORTEMENTALE</div><div class="mt-1 text-[17px] font-extrabold text-[#08243a]">Psychologie & discipline</div><div class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div class="metric"><b>${m.n}</b><span>Trades documentés</span></div><div class="metric"><b>${v(m.plan)}${m.plan==null?'':'%'}</b><span>Plan respecté</span></div><div class="metric"><b>${v(m.confidence)}/10</b><span>Confiance moyenne</span></div><div class="metric"><b>${v(m.stress)}/10</b><span>Stress moyen</span></div></div><div class="mt-3 grid gap-3 sm:grid-cols-3"><div class="beh"><b>FOMO</b><span>${m.fomo.n} trade(s) · WR ${v(m.fomo.wr)}% · P&L ${m.fomo.pnl>=0?'+':''}${m.fomo.pnl.toFixed(2)}</span></div><div class="beh"><b>Revenge trading</b><span>${m.revenge.n} trade(s) · WR ${v(m.revenge.wr)}% · P&L ${m.revenge.pnl>=0?'+':''}${m.revenge.pnl.toFixed(2)}</span></div><div class="beh"><b>Impulsion</b><span>${m.impulse.n} trade(s) · WR ${v(m.impulse.wr)}% · P&L ${m.impulse.pnl>=0?'+':''}${m.impulse.pnl.toFixed(2)}</span></div></div>`})}
function boot(){normalize();addFields();const f=$('quickForm');if(f&&!f.dataset.iamBound){f.addEventListener('submit',()=>{window.__iamEditingTradeId=f.dataset.editingId||null;savePsychology(snapshot())},true);f.dataset.iamBound='1'}fillExisting();renderAnalysis();window.addEventListener('iamtrader:data-updated',()=>{normalize();renderAnalysis()});new MutationObserver(()=>{addFields();fillExisting();renderAnalysis()}).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();