(()=>{
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const money=(x,c='USD')=>Number.isFinite(Number(x))?`${c==='USD'?'$':c+' '}${Number(x).toLocaleString('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2})}`:'—';
const num=(x,d=2)=>Number.isFinite(Number(x))?Number(x).toLocaleString('fr-FR',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
const KEYS={settings:'iamtrader_settings_v2',trades:'iamtrader_trades'};
const readTrades=()=>{try{return JSON.parse(localStorage.getItem(KEYS.trades)||'[]')}catch{return[]}};
const saveTrades=v=>localStorage.setItem(KEYS.trades,JSON.stringify(v.slice(0,500)));
const settings=()=>{try{return JSON.parse(localStorage.getItem(KEYS.settings)||'{}')}catch{return{}}};
const active=()=>{const s=settings();return (s.accounts||[]).find(a=>a.id===s.activeAccountId)||(s.accounts||[])[0]||null};
function validateLevels(direction,entry,sl,tp){
  if(![entry,sl,tp].every(Number.isFinite)) return 'Renseignez Entry, Stop Loss et Take Profit.';
  if(direction==='BUY' && !(sl<entry && entry<tp)) return 'BUY incohérent : le Stop Loss doit être inférieur à l’Entry et le Take Profit supérieur à l’Entry.';
  if(direction==='SELL' && !(tp<entry && entry<sl)) return 'SELL incohérent : le Take Profit doit être inférieur à l’Entry et le Stop Loss supérieur à l’Entry.';
  return '';
}
function ensureModal(){
 if($('tradeDetailModal')) return;
 document.body.insertAdjacentHTML('beforeend',`<div id="tradeDetailModal" class="fixed inset-0 z-[100] hidden items-center justify-center bg-slate-950/35 p-4 backdrop-blur-sm">
  <div id="tradeModalPanel" class="w-full max-w-3xl overflow-hidden rounded-2xl border border-line bg-white shadow-float">
   <div class="flex items-center justify-between border-b border-line px-5 py-4"><div><div class="kicker">DÉTAIL DU TRADE</div><h3 id="tradeModalTitle" class="mt-1 text-lg font-extrabold text-ink">—</h3></div><button id="tradeModalClose" class="grid h-9 w-9 place-items-center rounded-xl border border-line text-slate-500 hover:bg-slate-50">×</button></div>
   <div id="tradeModalBody" class="max-h-[72vh] overflow-y-auto p-5"></div>
   <div class="flex flex-wrap justify-end gap-2 border-t border-line bg-slate-50 px-5 py-4"><button id="tradeModalEdit" class="btn secondary">Modifier</button><button id="tradeModalDelete" class="btn secondary !border-red-200 !text-red-600">Supprimer</button><button id="tradeModalClose2" class="btn primary">Fermer</button></div>
  </div></div>`);
 const close=()=>{$('tradeDetailModal')?.classList.add('hidden');$('tradeDetailModal')?.classList.remove('flex')};
 $('tradeModalClose').onclick=close;$('tradeModalClose2').onclick=close;$('tradeDetailModal').addEventListener('click',e=>{if(e.target.id==='tradeDetailModal')close()});
}
function openTrade(id){ensureModal();const t=readTrades().find(x=>x.id===id);if(!t)return;const a=active();const pnl=Number(t.netPnl),risk=Number(t.riskAmount);$('tradeModalTitle').textContent=`${t.symbol||'Trade'} · ${t.direction||'—'}`;
 $('tradeModalBody').innerHTML=`<div class="grid gap-3 sm:grid-cols-4"><div class="rounded-xl bg-slate-50 p-3"><div class="text-[10px] muted">DATE</div><div class="mt-1 text-[12px] font-bold">${t.dateTime?new Date(t.dateTime).toLocaleString('fr-FR'):'—'}</div></div><div class="rounded-xl bg-slate-50 p-3"><div class="text-[10px] muted">R:R</div><div class="mt-1 mono text-[13px] font-bold">${num(t.rr)} </div></div><div class="rounded-xl bg-slate-50 p-3"><div class="text-[10px] muted">RISQUE</div><div class="mt-1 mono text-[13px] font-bold">${money(t.riskAmount,a?.currency)} · ${num(t.riskPercent)}%</div></div><div class="rounded-xl bg-slate-50 p-3"><div class="text-[10px] muted">R MULTIPLE</div><div class="mt-1 mono text-[13px] font-bold ${Number(t.rMultiple)>=0?'text-emerald-600':'text-red-500'}">${t.rMultiple!=null?num(t.rMultiple)+' R':'—'}</div></div></div>
 <div class="mt-4 grid gap-3 sm:grid-cols-3"><div><div class="text-[10px] muted">ENTRY</div><div class="mono mt-1 font-bold">${num(t.entry)}</div></div><div><div class="text-[10px] muted">STOP LOSS</div><div class="mono mt-1 font-bold">${num(t.sl)}</div></div><div><div class="text-[10px] muted">TAKE PROFIT</div><div class="mono mt-1 font-bold">${num(t.tp)}</div></div></div>
 <div class="mt-4 rounded-xl border border-line p-4"><div class="text-[10px] font-bold tracking-wider muted">NOTE DU TRADE</div><div class="mt-2 whitespace-pre-wrap text-[13px] leading-6">${esc(t.note||'Aucune note renseignée.')}</div></div>
 <div class="mt-4 grid gap-3 sm:grid-cols-2"><div class="rounded-xl border border-line p-3"><div class="text-[10px] font-bold muted">PREUVE AVANT</div>${t.beforeImageUrl?`<a href="${esc(t.beforeImageUrl)}" target="_blank" rel="noopener" class="mt-2 block overflow-hidden rounded-lg bg-slate-50"><img src="${esc(t.beforeImageUrl)}" alt="Preuve avant" class="h-40 w-full object-cover" onerror="this.parentElement.innerHTML='<div class=\"grid h-40 place-items-center text-xs muted\">Image indisponible · ouvrir le lien</div>'"></a>`:'<div class="mt-2 grid h-40 place-items-center rounded-lg bg-slate-50 text-xs muted">Aucune preuve</div>'}</div><div class="rounded-xl border border-line p-3"><div class="text-[10px] font-bold muted">PREUVE FINALE</div>${t.afterImageUrl?`<a href="${esc(t.afterImageUrl)}" target="_blank" rel="noopener" class="mt-2 block overflow-hidden rounded-lg bg-slate-50"><img src="${esc(t.afterImageUrl)}" alt="Preuve finale" class="h-40 w-full object-cover" onerror="this.parentElement.innerHTML='<div class=\"grid h-40 place-items-center text-xs muted\">Image indisponible · ouvrir le lien</div>'"></a>`:'<div class="mt-2 grid h-40 place-items-center rounded-lg bg-slate-50 text-xs muted">Aucune preuve finale</div>'}</div></div>`;
 $('tradeModalEdit').onclick=()=>{closeTradeModal();editTrade(id)};
 $('tradeModalDelete').onclick=()=>confirmAction('Supprimer définitivement ce trade ?','Cette action est irréversible.',()=>{const next=readTrades().filter(x=>x.id!==id);saveTrades(next);closeTradeModal();if(typeof renderAll==='function')renderAll()});
 const modal=$('tradeDetailModal');modal.classList.remove('hidden');modal.classList.add('flex');
}
function closeTradeModal(){$('tradeDetailModal')?.classList.add('hidden');$('tradeDetailModal')?.classList.remove('flex')}
function confirmAction(title,body,yes){const ok=window.confirm(`${title}\n\n${body}`);if(ok)yes()}
function editTrade(id){const t=readTrades().find(x=>x.id===id);if(!t)return;const form=$('quickForm')||document.querySelector('form:has(#qEntry)');if(!form)return;['qAccount','qSymbol','qDirection','qDate','qEntry','qSL','qTP','qQty','qMult','qClose','qNote','qBefore','qAfter'].forEach(k=>{if($(k))$(k).value=t[k.replace(/^q/,'').replace('Account','account').replace('Symbol','symbol').replace('Direction','direction').replace('Date','dateTime').replace('Entry','entry').replace('SL','sl').replace('TP','tp').replace('Qty','qty').replace('Mult','mult').replace('Close','close').replace('Note','note').replace('Before','beforeImageUrl').replace('After','afterImageUrl')]||t[k]||''});form.dataset.editingId=id;navigate?.('quick');toast?.('Modification : vérifiez puis enregistrez le trade.');}
function closeEditorMarker(){const f=$('quickForm')||document.querySelector('form:has(#qEntry)');if(f)delete f.dataset.editingId}
function addPsychologyFields(){const note=$('qNote');if(!note||$('qEmotion'))return;const box=document.createElement('div');box.id='psychologyFields';box.className='mt-4 rounded-2xl border border-brand/15 bg-brand/[.035] p-4';box.innerHTML=`<div class="flex items-center justify-between gap-3"><div><div class="text-[10px] font-extrabold tracking-[.12em] text-brand">LECTURE PSYCHOLOGIQUE</div><div class="mt-1 text-[12px] font-bold text-ink">Comment prends-tu cette décision ?</div></div><span class="rounded-full bg-white px-2 py-1 text-[9px] font-bold text-slate-500">OPTIONNEL · RECOMMANDÉ</span></div><div class="mt-4 grid gap-3 sm:grid-cols-2"><label class="text-[11px] font-semibold">État avant<select id="qEmotion" class="field mt-1"><option value="">Sélectionner</option><option>Calme</option><option>Confiant</option><option>Incertain</option><option>Stressé</option><option>FOMO</option><option>Frustré</option><option>Pressé</option><option>Excité</option></select></label><label class="text-[11px] font-semibold">Confiance dans le setup<select id="qConfidence" class="field mt-1"><option value="">—</option><option value="1">1 / 5</option><option value="2">2 / 5</option><option value="3">3 / 5</option><option value="4">4 / 5</option><option value="5">5 / 5</option></select></label><label class="text-[11px] font-semibold">Motif d’entrée<select id="qReason" class="field mt-1"><option value="">Sélectionner</option><option>Setup conforme</option><option>Opportunité exceptionnelle</option><option>FOMO</option><option>Revenge trading</option><option>Impulsion</option><option>Autre</option></select></label><label class="text-[11px] font-semibold">Plan respecté<select id="qPlan" class="field mt-1"><option value="">—</option><option value="yes">Oui</option><option value="partial">Partiellement</option><option value="no">Non</option></select></label><label class="text-[11px] font-semibold sm:col-span-2">État après le trade<select id="qAfterEmotion" class="field mt-1"><option value="">—</option><option>Calme</option><option>Satisfait</option><option>Déçu</option><option>Frustré</option><option>En colère</option><option>Euphorique</option><option>Stressé</option></select></label></div>`;note.parentElement?.after(box)}
function validateForm(e){const f=e.target;if(!f||!$('qEntry'))return;const direction=$('qDirection')?.value,entry=Number($('qEntry')?.value),sl=Number($('qSL')?.value),tp=Number($('qTP')?.value);const err=validateLevels(direction,entry,sl,tp);if(err){e.preventDefault();e.stopImmediatePropagation();alert(err);return false}return true}
function afterSavePsychology(){setTimeout(()=>{const f=$('quickForm')||document.querySelector('form:has(#qEntry)');if(!f||f.dataset.editingId)return;const all=readTrades();const symbol=$('qSymbol')?.value;const candidates=all.filter(t=>t.symbol===symbol);const t=candidates[0];if(!t)return;const psych={emotion:$('qEmotion')?.value||null,confidence:Number($('qConfidence')?.value)||null,reason:$('qReason')?.value||null,planFollowed:$('qPlan')?.value||null,afterEmotion:$('qAfterEmotion')?.value||null};if(Object.values(psych).some(Boolean)){t.psychology=psych;saveTrades(all);if(typeof renderAll==='function')renderAll()}},0)}
function augmentJournal(){const rows=$('journalRows');if(!rows)return;rows.querySelectorAll('tr').forEach(row=>{if(row.dataset.enhanced)return;const buttons=row.querySelectorAll('button');let label=row.textContent.trim();const match=readTrades().find(t=>label.includes(String(t.symbol||''))&&label.includes(String(t.direction||'')));if(!match)return;const cell=document.createElement('td');cell.className='px-3 py-3 text-right';cell.innerHTML=`<button title="Détails du trade" class="trade-more grid h-8 w-8 place-items-center rounded-lg border border-line bg-white text-slate-500 hover:border-brand hover:text-brand">•••</button>`;cell.querySelector('button').onclick=()=>openTrade(match.id);row.appendChild(cell);row.dataset.enhanced='1';if(buttons.length){buttons.forEach(b=>{if(/supprimer|delete|effacer/i.test(b.textContent||'')){const old=b.onclick;b.onclick=e=>{e.preventDefault();confirmAction('Supprimer ce trade ?','Cette action est irréversible.',()=>old?.call(b,e))}}})}})}
function boot(){ensureModal();addPsychologyFields();const form=$('quickForm')||document.querySelector('form:has(#qEntry)');if(form){form.addEventListener('submit',validateForm,true);form.addEventListener('submit',afterSavePsychology,false)}const observer=new MutationObserver(()=>{addPsychologyFields();augmentJournal()});observer.observe(document.body,{subtree:true,childList:true});augmentJournal();window.__iamtraderEnhancements={openTrade,validateLevels,confirmAction}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
